


<div align="center">
  <h1> Association Rule Learning Using FP-
Growth</h1>
</div>

In [1]:
dataset = [['Milk', 'Curd', 'Biscuit', 'Bread', 'Eggs', 'Banana'],
['Coffee', 'Curd', 'Biscuit', 'Bread', 'Eggs', 'Banana'],
['Milk', 'Salt', 'Bread', 'Eggs'],
['Milk', 'Unicorn', 'Salt', 'Bread', 'Banana'],
['Salt', 'Curd', 'Sugar', 'Bread', 'Ice cream', 'Eggs']]

In [2]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
te = TransactionEncoder()
te_array = te.fit_transform(dataset)
te_array

array([[ True,  True,  True, False,  True,  True, False,  True, False,
        False, False],
       [ True,  True,  True,  True,  True,  True, False, False, False,
        False, False],
       [False, False,  True, False, False,  True, False,  True,  True,
        False, False],
       [ True, False,  True, False, False, False, False,  True,  True,
        False,  True],
       [False, False,  True, False,  True,  True,  True, False,  True,
         True, False]])

In [3]:
te.columns_

['Banana',
 'Biscuit',
 'Bread',
 'Coffee',
 'Curd',
 'Eggs',
 'Ice cream',
 'Milk',
 'Salt',
 'Sugar',
 'Unicorn']

In [4]:
df = pd.DataFrame(te_array, columns=te.columns_)
df

,Banana,Biscuit,Bread,Coffee,Curd,Eggs,Ice cream,Milk,Salt,Sugar,Unicorn
0,True,True,True,False,True,True,False,True,False,False,False
1,True,True,True,True,True,True,False,False,False,False,False
2,False,False,True,False,False,True,False,True,True,False,False
3,True,False,True,False,False,False,False,True,True,False,True
4,False,False,True,False,True,True,True,False,True,True,False

In [5]:
from mlxtend.frequent_patterns import fpgrowth
fpgrowth(df, min_support=0.6) #Setting the threshold to 60%

    support   itemsets
0       1.0        (2)
1       0.8        (5)
2       0.6        (7)
3       0.6        (4)
4       0.6        (0)
5       0.6        (8)
6       0.8     (2, 5)
7       0.6     (2, 7)
8       0.6     (4, 5)
9       0.6     (2, 4)
10      0.6  (2, 4, 5)
11      0.6     (0, 2)
12      0.6     (8, 2)

In [6]:
fpgrowth(df, min_support=0.6, use_colnames=True)

    support             itemsets
0       1.0              (Bread)
1       0.8               (Eggs)
2       0.6               (Milk)
3       0.6               (Curd)
4       0.6             (Banana)
5       0.6               (Salt)
6       0.8        (Eggs, Bread)
7       0.6        (Milk, Bread)
8       0.6         (Eggs, Curd)
9       0.6        (Curd, Bread)
10      0.6  (Eggs, Curd, Bread)
11      0.6      (Banana, Bread)
12      0.6        (Salt, Bread)